from matplotlib import pyplot
def table_plot(df, title, outputPath):
    fig, ax = pyplot.subplots(figsize=(12, 6))
    ax.axis('off')

    tab = ax.table(cellText=df.values,
                   colLabels=df.columns,
                   colLoc="center",
                   rowLabels=df.index,
                   rowLoc="center",
                   loc='center',
                   )
    tab.auto_set_column_width(col=list(range(len(df.columns))))
    ax.set_title(title)
    ax.text(.5, .5, "generated by lapi\n@Weibo, @Zhihu, @Note", transform=ax.transAxes,
            fontsize=30, color='gray', alpha=0.3,
            ha='center', va='center', rotation=30)
    pyplot.savefig(outputPath)